# app/modules/notifications/notification_constants.py

class NotificationType:
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
    TASK_UPDATED = "TASK_UPDATED"

    PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED"
    PROJECT_UPDATED = "PROJECT_UPDATED"

    ACTIVITY_CREATED = "ACTIVITY_CREATED"
    SYSTEM = "SYSTEM"